language: dart
dart:
  - stable

dart_task:
  - test: --platform vm
  - test: --platform chrome

script:
  - pub global activate test_coverage
  - pub global run test_coverage
  - bash <(curl -s https://codecov.io/bash)