name: connectanum
homepage: https://github.com/konsultaner/connectanum-dart
version: 1.0.10
description: >-
  This is a WAMP client (Web Application Messaging Protocol) implementation for the dart language and flutter projects.
dependencies:
  saslprep: ^1.0.0
  pointycastle: ^2.0.0
  logging: ^0.11.4
  pedantic: ^1.9.0
  meta: ^1.1.8
dev_dependencies:
  test: ^1.14.2
  stream_channel: 2.0.0
environment:
  sdk: ">=2.3.0 <3.0.0"
