name: connectanum
homepage: https://github.com/konsultaner/connectanum-dart
version: 1.0.14
description: >-
  This is a WAMP client (Web Application Messaging Protocol) implementation for the dart language and flutter projects.
dependencies:
  saslprep: ^1.0.0
  pointycastle: ^2.0.0
  pinenacl: ^0.1.5
  logging: ^0.11.4
  pedantic: ^1.9.2
  meta: ^1.1.8
  msgpack_dart: ^0.0.7
dev_dependencies:
  test: ^1.14.2
  stream_channel: 2.0.0
environment:
  sdk: ">=2.3.0 <3.0.0"
